spring:
  application:
    name: eureka-server
server:
  port: 8070
eureka:
  instance:
   hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
zuul:
  routes:
    app1:
      path: /app1/**
      StripPrefix: false
      url: http://localhost:8071
    app2:
      path: /app2/**
      StripPrefix: false
      url: http://localhost:8072